version: '3'
services:
  node0:
    build: .
    environment:
      NODE_ID: 0
    container_name: node0
    ports:
      - "5000:5000"

  node1:
    build: .
    environment:
      NODE_ID: 1
    container_name: node1
    ports:
      - "5001:5000"

  node2:
    build: .
    environment:
      NODE_ID: 2
    container_name: node2
    ports:
      - "5002:5000"
